package org.citruscircuits.scout_viewer_2016_android;

import android.graphics.Color;

import java.util.HashMap;
import java.util.Map;

/**
 * Created by citruscircuits on 1/16/16.
 */
public class Constants {
    public static final String ROOT_FIREBASE_PATH = "https://1678-scouting-2016.firebaseio.com/";
    public static final String[] DRAWER_TITLES = {"Recent Matches", "Upcoming Matches", "Our Schedule", "Starred Matches", "Schedule", "Seeding", "Predicted Seeding", "First Pick", "Second Pick", "Super Data"};
    public static final String MATCHES_PATH = ROOT_FIREBASE_PATH + "Matches";
    public static final String TEAMS_PATH = ROOT_FIREBASE_PATH + "Teams";
    public static final String TEAM_IN_MATCH_DATAS_PATH = ROOT_FIREBASE_PATH + "TeamInMatchDatas";
    public static final String TEAMS_UPDATED_ACTION = "org.citruscircuits.scout_viewer_2016_android.teamsupdated";
    public static final String MATCHES_UPDATED_ACTION = "org.citruscircuits.scout_viewer_2016_android.matchesupdated";
    public static final String TEAM_IN_MATCH_DATAS_UPDATED_ACTION = "org.citruscircuits.scout_viewer_2016_android.teaminmatchdatasupdated";
    public static final String NEW_TEAM_PHOTO_ACTION = "org.citruscircuits.scout_viewer_2016_android.newteamphoto";
    public static final String NEW_MATCH_PLAYED_ACTION = "org.citruscircuits.scout_viewer_2016_android.newmatchplayed";
    public static final String STARS_MODIFIED_ACTION = "org.citruscircuits.scout_viewer_2016_android.starsmodified";
    public static final String[] MATCH_SCOPES = {"Match", "Team"};
    public static final String[] TEAM_SCOPES = {"Team"};
    public static final int STAR_COLOR = Color.argb(255, 255, 255, 204);
    public static final int TEAM_NUMBER = 1678;
    public static final Map<String, String> KEYS_TO_TITLES = new HashMap<String, String> () {
        {
            put("calculatedData.avgHighShotsAuto", "Avg. Auto High Shots");
            put("calculatedData.avgLowShotsAuto", "Avg. Auto Low Shots");
            put("calculatedData.avgHighShotsTele", "Avg. Tele High Shots");
            put("calculatedData.avgLowShotsTele", "Avg. Tele Low Shots");
            put("pitFrontBumperWidth", "Bumper Width");
            put("pitLowBarCapability", "Can Low Bar?");
            put("pitPotentialLowBarCapability", "Could Low Bar?");
            put("pitPotentialMidlineBallCapability", "Could Midline?");
            put("pitDriveBaseWidth", "Base Width");
            put("pitDriveBaseLength", "Base Length");
            put("pitBumperHeight", "Bumper Height");
            put("pitPotentialShotBlockerCapability", "Could Block?");
            put("pitNotes", "Notes");
            put("pitOrganization", "Pit Organization");
            put("pitNumberOfWheels", "Num. Wheels");
            put("calculatedData.firstPickAbility", "First Pick Ability");
            put("calculatedData.driverAbility", "Driver Ability");
            put("calculatedData.highShotAccuracyAuto", "Auto High Shot Acc.");
            put("calculatedData.lowShotAccuracyAuto", "Auto Low Shot Acc.");
            put("calculatedData.highShotAccuracyTele", "Tele High Shot Acc.");
            put("calculatedData.lowShotAccuracyTele", "Tele Low Shot Acc.");
            put("calculatedData.avgGroundIntakes", "Avg. Ground Intakes");
            put("calculatedData.avgHighShotsTele", "Avg. Tele High");
            put("calculatedData.avgLowShotsTele", "Avg. Tele Low");
            put("calculatedData.avgShotsBlocked", "Avg. Shots Blocked");
            put("calculatedData.avgHighShotsAuto", "Avg. Auto High");
            put("calculatedData.avgLowShotsAuto", "Avg. Auto Low");
            put("calculatedData.avgMidlineBallsIntakedAuto", "Avg. Mid. Balls");
            put("calculatedData.avgBallsKnockedOffMidlineAuto", "Avg. Mid. Knocked");
            put("calculatedData.avgTorque", "Avg. Torque");
            put("calculatedData.avgSpeed", "Avg. Speed");
            put("calculatedData.avgEvasion", "Avg. Evasion");
            put("calculatedData.avgDefense", "Avg. Defense");
            put("calculatedData.avgBallControl", "Avg. Ball Control");
            put("calculatedData.RScoreTorque", "Torque");
            put("calculatedData.RScoreSpeed", "Speed");
            put("calculatedData.RScoreEvasion", "Evasion");
            put("calculatedData.RScoreDefense", "Defense");
            put("calculatedData.RScoreBallControl", "Ball Control");
            put("calculatedData.RScoreDrivingAbility", "Driving Ability");
            put("calculatedData.disfunctionalPercentage", "Disfunctional");
            put("calculatedData.reachPercentage", "Reach");
            put("calculatedData.disabledPercentage", "Disabled");
            put("calculatedData.incapacitatedPercentage", "Incapacitated");
            put("calculatedData.scalePercentage", "Scale");
            put("calculatedData.challengePercentage", "Challenge");
            put("calculatedData.siegePower", "Siege Power");
            put("calculatedData.siegeConsistency", "Siege Consistency");
            put("calculatedData.siegeAbility", "Siege Ability");
            put("calculatedData.predictedNumRPs", "Predicted RPs");
            put("calculatedData.numRPs", "Num. RPs");
            put("calculatedData.numAutoPoints", "Num. Auto Pts.");
            put("calculatedData.numScaleAndChallengePoints", "Num. S&C Pts.");
            put("calculatedData.predictedSeed", "Predicted Seed");
            put("calculatedData.actualSeed", "Seed");
            put("calculatedData.avgSuccessfulTimesCrossedDefensesAuto.a.pc", "Avg. Auto PC Cross");
            put("calculatedData.avgSuccessfulTimesCrossedDefensesAuto.a.cdf", "Avg. Auto CDF Cross");
            put("calculatedData.avgSuccessfulTimesCrossedDefensesAuto.b.mt", "Avg. Auto MT Cross");
            put("calculatedData.avgSuccessfulTimesCrossedDefensesAuto.b.rp", "Avg. Auto RP Cross");
            put("calculatedData.avgSuccessfulTimesCrossedDefensesAuto.c.db", "Avg. Auto DB Cross");
            put("calculatedData.avgSuccessfulTimesCrossedDefensesAuto.c.sp", "Avg. Auto SP Cross");
            put("calculatedData.avgSuccessfulTimesCrossedDefensesAuto.d.rw", "Avg. Auto RW Cross");
            put("calculatedData.avgSuccessfulTimesCrossedDefensesAuto.d.rt", "Avg. Auto RT Cross");
            put("calculatedData.avgSuccessfulTimesCrossedDefensesAuto.e.lb", "Avg. Auto LB Cross");
            put("calculatedData.avgFailedTimesCrossedDefensesAuto.a.pc", "Avg. Auto PC Fails");
            put("calculatedData.avgFailedTimesCrossedDefensesAuto.a.cdf", "Avg. Auto CDF Fails");
            put("calculatedData.avgFailedTimesCrossedDefensesAuto.b.mt", "Avg. Auto MT Fails");
            put("calculatedData.avgFailedTimesCrossedDefensesAuto.b.rp", "Avg. Auto RP Fails");
            put("calculatedData.avgFailedTimesCrossedDefensesAuto.c.db", "Avg. Auto DB Fails");
            put("calculatedData.avgFailedTimesCrossedDefensesAuto.c.sp", "Avg. Auto SP Fails");
            put("calculatedData.avgFailedTimesCrossedDefensesAuto.d.rw", "Avg. Auto RW Fails");
            put("calculatedData.avgFailedTimesCrossedDefensesAuto.d.rt", "Avg. Auto RT Fails");
            put("calculatedData.avgFailedTimesCrossedDefensesAuto.e.lb", "Avg. Auto LB Fails");
            put("calculatedData.avgSuccessfulTimesCrossedDefensesTele.a.pc", "Avg. Tele PC Cross");
            put("calculatedData.avgSuccessfulTimesCrossedDefensesTele.a.cdf", "Avg. Tele CDF Cross");
            put("calculatedData.avgSuccessfulTimesCrossedDefensesTele.b.mt", "Avg. Tele MT Cross");
            put("calculatedData.avgSuccessfulTimesCrossedDefensesTele.b.rp", "Avg. Tele RP Cross");
            put("calculatedData.avgSuccessfulTimesCrossedDefensesTele.c.db", "Avg. Tele DB Cross");
            put("calculatedData.avgSuccessfulTimesCrossedDefensesTele.c.sp", "Avg. Tele SP Cross");
            put("calculatedData.avgSuccessfulTimesCrossedDefensesTele.d.rw", "Avg. Tele RW Cross");
            put("calculatedData.avgSuccessfulTimesCrossedDefensesTele.d.rt", "Avg. Tele RT Cross");
            put("calculatedData.avgSuccessfulTimesCrossedDefensesTele.e.lb", "Avg. Tele LB Cross");
            put("calculatedData.avgFailedTimesCrossedDefensesTele.a.pc", "Avg. Tele PC Fails");
            put("calculatedData.avgFailedTimesCrossedDefensesTele.a.cdf", "Avg. Tele CDF Fails");
            put("calculatedData.avgFailedTimesCrossedDefensesTele.b.mt", "Avg. Tele MT Fails");
            put("calculatedData.avgFailedTimesCrossedDefensesTele.b.rp", "Avg. Tele RP Fails");
            put("calculatedData.avgFailedTimesCrossedDefensesTele.c.db", "Avg. Tele DB Fails");
            put("calculatedData.avgFailedTimesCrossedDefensesTele.c.sp", "Avg. Tele SP Fails");
            put("calculatedData.avgFailedTimesCrossedDefensesTele.d.rw", "Avg. Tele RW Fails");
            put("calculatedData.avgFailedTimesCrossedDefensesTele.d.rt", "Avg. Tele RT Fails");
            put("calculatedData.avgFailedTimesCrossedDefensesTele.e.lb", "Avg. Tele LB Fails");
            put("didGetIncapacitated", "Incapacitated?");
            put("didGetDisabled", "Disabled?");
            put("rankTorque", "Torque");
            put("rankSpeed", "Speed");
            put("rankEvasion", "Evasion");
            put("rankDefense", "Defense");
            put("rankBallControl", "Ball Control");
            put("ballsIntakedAuto", "Mid. Balls Int.");
            put("numHighShotsMadeAuto", "Auto High Shots");
            put("numLowShotsMadeAuto", "Auto Low Shots");
            put("numHighShotsMissedAuto", "Auto High Misses");
            put("numLowShotsMissedAuto", "Auto Low Misses");
            put("didReachAuto", "Reach?");
            put("numHighShotsMadeTele", "Tele High Shots");
            put("numLowShotsMadeTele", "Tele Low Shots");
            put("numHighShotsMissedTele", "Tele High Misses");
            put("numLowShotsMissedTele", "Tele Low Misses");
            put("numGroundIntakesTele", "Tele Ground Intakes");
            put("numShotsBlockedTele", "Shots Blocked");
            put("didScaleTele", "Scale?");
            put("didChallengeTele", "Challenge?");
            put("timesSuccessfulCrossedDefensesTele.a.pc", "Tele PC Cross");
            put("timesSuccessfulCrossedDefensesTele.a.cdf", "Tele CDF Cross");
            put("timesSuccessfulCrossedDefensesTele.b.mt", "Tele MT Cross");
            put("timesSuccessfulCrossedDefensesTele.b.rp", "Tele RP Cross");
            put("timesSuccessfulCrossedDefensesTele.c.db", "Tele DB Cross");
            put("timesSuccessfulCrossedDefensesTele.c.sp", "Tele SP Cross");
            put("timesSuccessfulCrossedDefensesTele.d.rw", "Tele RW Cross");
            put("timesSuccessfulCrossedDefensesTele.d.rt", "Tele RT Cross");
            put("timesSuccessfulCrossedDefensesTele.e.lb", "Tele LB Cross");
            put("timesFailedCrossedDefensesTele.a.pc", "Tele PC Fail");
            put("timesFailedCrossedDefensesTele.a.cdf", "Tele CDF Fail");
            put("timesFailedCrossedDefensesTele.b.mt", "Tele MT Fail");
            put("timesFailedCrossedDefensesTele.b.rp", "Tele RP Fail");
            put("timesFailedCrossedDefensesTele.c.db", "Tele DB Fail");
            put("timesFailedCrossedDefensesTele.c.sp", "Tele SP Fail");
            put("timesFailedCrossedDefensesTele.d.rw", "Tele RW Fail");
            put("timesFailedCrossedDefensesTele.d.rt", "Tele RT Fail");
            put("timesFailedCrossedDefensesTele.e.lb", "Tele LB Fail");
            put("timesSuccessfulCrossedDefensesAuto.a.pc", "Auto PC Cross");
            put("timesSuccessfulCrossedDefensesAuto.a.cdf", "Auto CDF Cross");
            put("timesSuccessfulCrossedDefensesAuto.b.mt", "Auto MT Cross");
            put("timesSuccessfulCrossedDefensesAuto.b.rp", "Auto RP Cross");
            put("timesSuccessfulCrossedDefensesAuto.c.db", "Auto DB Cross");
            put("timesSuccessfulCrossedDefensesAuto.c.sp", "Auto SP Cross");
            put("timesSuccessfulCrossedDefensesAuto.d.rw", "Auto RW Cross");
            put("timesSuccessfulCrossedDefensesAuto.d.rt", "Auto RT Cross");
            put("timesSuccessfulCrossedDefensesAuto.e.lb", "Auto LB Cross");
            put("timesFailedCrossedDefensesAuto.a.pc", "Auto PC Fail");
            put("timesFailedCrossedDefensesAuto.a.cdf", "Auto CDF Fail");
            put("timesFailedCrossedDefensesAuto.b.mt", "Auto MT Fail");
            put("timesFailedCrossedDefensesAuto.b.rp", "Auto RP Fail");
            put("timesFailedCrossedDefensesAuto.c.db", "Auto DB Fail");
            put("timesFailedCrossedDefensesAuto.c.sp", "Auto SP Fail");
            put("timesFailedCrossedDefensesAuto.d.rw", "Auto RW Fail");
            put("timesFailedCrossedDefensesAuto.d.rt", "Auto RT Fail");
            put("timesFailedCrossedDefensesAuto.e.lb", "Auto LB Fail");
            put("superNotes", "Notes");
            put("numBallsKnockedOffMidlineAuto", "Knocked Off Mid.");
            put("numBallsKnockedOffMidlineAuto", "Knocked Off Mid.");
            put("calculatedData.citrusDPR", "Citrus DPR");
            put("calculatedData.overallSecondPickAbility", "Overall Second Pick Ability");
            put("cdf", "Cheval de Frise");
            put("pc", "Portcullis");
            put("mt", "Moat");
            put("rp", "Ramparts");
            put("db", "Drawbridge");
            put("sp", "Sally Port");
            put("rt", "Rough Terrain");
            put("rw", "Rock Wall");
            put("lb", "Low Bar");
            put("calculatedData.avgSuccessfulTimesCrossedDefenses.a.pc", "Avg. PC Cross");
            put("calculatedData.avgSuccessfulTimesCrossedDefenses.a.cdf", "Avg. CDF Cross");
            put("calculatedData.avgSuccessfulTimesCrossedDefenses.b.mt", "Avg. MT Cross");
            put("calculatedData.avgSuccessfulTimesCrossedDefenses.b.rp", "Avg. RP Cross");
            put("calculatedData.avgSuccessfulTimesCrossedDefenses.c.db", "Avg. DB Cross");
            put("calculatedData.avgSuccessfulTimesCrossedDefenses.c.sp", "Avg. SP Cross");
            put("calculatedData.avgSuccessfulTimesCrossedDefenses.d.rw", "Avg. RW Cross");
            put("calculatedData.avgSuccessfulTimesCrossedDefenses.d.rt", "Avg. RT Cross");
            put("calculatedData.avgSuccessfulTimesCrossedDefenses.e.lb", "Avg. LB Cross");
            put("teamNumber", "Team Number");
            put("matchNumber", "Match Number");
            put("matches", "Matches");
        }
    };

    public static final Map<String, String> DATA_TO_GRAPH = new HashMap<String, String> () {
        {
            put("calculatedData.avgHighShotsAuto", "numHighShotsMadeAuto");
            put("calculatedData.avgLowShotsAuto", "numLowShotsMadeAuto");
            put("calculatedData.avgHighShotsTele", "numHighShotsMadeTele");
            put("calculatedData.avgLowShotsTele", "numLowShotsMadeTele");
            put("calculatedData.firstPickAbility", "calculatedData.firstPickAbility");
            put("calculatedData.highShotAccuracyAuto", "calculatedData.highShotAccuracyAuto");
            put("calculatedData.lowShotAccuracyAuto", "calculatedData.lowShotAccuracyAuto");
            put("calculatedData.highShotAccuracyTele", "calculatedData.highShotAccuracyTele");
            put("calculatedData.lowShotAccuracyTele", "calculatedData.lowShotAccuracyTele");
            put("calculatedData.avgGroundIntakes", "numGroundIntakesTele");
            put("calculatedData.avgHighShotsTele", "numHighShotsMadeTele");
            put("calculatedData.avgLowShotsTele", "numLowShotsMadeTele");
            put("calculatedData.avgShotsBlocked", "numShotsBlockedTele");
            put("calculatedData.avgHighShotsAuto", "numHighShotsMadeAuto");
            put("calculatedData.avgLowShotsAuto", "numLowShotsAuto");
            put("calculatedData.avgMidlineBallsIntakedAuto", "calculatedData.numBallsIntakedOffMidlineAuto");
            put("calculatedData.avgBallsKnockedOffMidlineAuto", "numBallsKnockedOffMidlineAuto");
            put("calculatedData.avgTorque", "rankTorque");
            put("calculatedData.avgSpeed", "rankSpeed");
            put("calculatedData.avgEvasion", "rankEvasion");
            put("calculatedData.avgDefense", "rankDefense");
            put("calculatedData.avgBallControl", "rankBallControl");
            put("calculatedData.RScoreTorque", "calculatedData.RScoreTorque");
            put("calculatedData.RScoreSpeed", "calculatedData.RScoreSpeed");
            put("calculatedData.RScoreEvasion", "calculatedData.RScoreEvasion");
            put("calculatedData.RScoreDefense", "calculatedData.RScoreDefense");
            put("calculatedData.RScoreBallControl", "calculatedData.RScoreBallControl");
            put("calculatedData.RScoreDrivingAbility", "calculatedData.RScoreDrivingAbility");
            put("calculatedData.reachPercentage", "didReachAuto");
            put("calculatedData.disabledPercentage", "didGetDisabled");
            put("calculatedData.incapacitatedPercentage", "didGetIncapacitated");
            put("calculatedData.scalePercentage", "didScaleTele");
            put("calculatedData.challengePercentage", "didChallengeTele");
            put("calculatedData.siegePower", "calculatedData.siegePower");
            put("calculatedData.siegeConsistency", "calculatedData.siegeConsistency");
            put("calculatedData.siegeAbility", "calculatedData.siegeAbility");
            put("calculatedData.numAutoPoints", "calculatedData.numAutoPoints");
            put("calculatedData.numScaleAndChallengePoints", "calculatedData.numScaleAndChallengePoints");
            put("calculatedData.avgSuccessfulTimesCrossedDefensesAuto.a.pc", "timesSuccessfulCrossedDefensesAuto.a.pc");
            put("calculatedData.avgSuccessfulTimesCrossedDefensesAuto.a.cdf", "timesSuccessfulCrossedDefensesAuto.a.cdf");
            put("calculatedData.avgSuccessfulTimesCrossedDefensesAuto.b.mt", "timesSuccessfulCrossedDefensesAuto.b.mt");
            put("calculatedData.avgSuccessfulTimesCrossedDefensesAuto.b.rp", "timesSuccessfulCrossedDefensesAuto.b.rp");
            put("calculatedData.avgSuccessfulTimesCrossedDefensesAuto.c.db", "timesSuccessfulCrossedDefensesAuto.c.db");
            put("calculatedData.avgSuccessfulTimesCrossedDefensesAuto.c.sp", "timesSuccessfulCrossedDefensesAuto.c.sp");
            put("calculatedData.avgSuccessfulTimesCrossedDefensesAuto.d.rw", "timesSuccessfulCrossedDefensesAuto.d.rw");
            put("calculatedData.avgSuccessfulTimesCrossedDefensesAuto.d.rt", "timesSuccessfulCrossedDefensesAuto.d.rt");
            put("calculatedData.avgSuccessfulTimesCrossedDefensesAuto.e.lb", "timesSuccessfulCrossedDefensesAuto.e.lb");
            put("calculatedData.avgFailedTimesCrossedDefensesAuto.a.pc", "timesFailedCrossedDefensesAuto.a.pc");
            put("calculatedData.avgFailedTimesCrossedDefensesAuto.a.cdf", "timesFailedCrossedDefensesAuto.a.cdf");
            put("calculatedData.avgFailedTimesCrossedDefensesAuto.b.mt", "timesFailedCrossedDefensesAuto.b.mt");
            put("calculatedData.avgFailedTimesCrossedDefensesAuto.b.rp", "timesFailedCrossedDefensesAuto.b.rp");
            put("calculatedData.avgFailedTimesCrossedDefensesAuto.c.db", "timesFailedCrossedDefensesAuto.c.db");
            put("calculatedData.avgFailedTimesCrossedDefensesAuto.c.sp", "timesFailedCrossedDefensesAuto.c.sp");
            put("calculatedData.avgFailedTimesCrossedDefensesAuto.d.rw", "timesFailedCrossedDefensesAuto.d.rw");
            put("calculatedData.avgFailedTimesCrossedDefensesAuto.d.rt", "timesFailedCrossedDefensesAuto.d.rt");
            put("calculatedData.avgFailedTimesCrossedDefensesAuto.e.lb", "timesFailedCrossedDefensesAuto.e.lb");
            put("calculatedData.avgSuccessfulTimesCrossedDefensesTele.a.pc", "timesSuccessfulCrossedDefensesTele.a.pc");
            put("calculatedData.avgSuccessfulTimesCrossedDefensesTele.a.cdf", "timesSuccessfulCrossedDefensesTele.a.cdf");
            put("calculatedData.avgSuccessfulTimesCrossedDefensesTele.b.mt", "timesSuccessfulCrossedDefensesTele.b.mt");
            put("calculatedData.avgSuccessfulTimesCrossedDefensesTele.b.rp", "timesSuccessfulCrossedDefensesTele.b.rp");
            put("calculatedData.avgSuccessfulTimesCrossedDefensesTele.c.db", "timesSuccessfulCrossedDefensesTele.c.db");
            put("calculatedData.avgSuccessfulTimesCrossedDefensesTele.c.sp", "timesSuccessfulCrossedDefensesTele.c.sp");
            put("calculatedData.avgSuccessfulTimesCrossedDefensesTele.d.rw", "timesSuccessfulCrossedDefensesTele.d.rw");
            put("calculatedData.avgSuccessfulTimesCrossedDefensesTele.d.rt", "timesSuccessfulCrossedDefensesTele.d.rt");
            put("calculatedData.avgSuccessfulTimesCrossedDefensesTele.e.lb", "timesSuccessfulCrossedDefensesTele.e.lb");
            put("calculatedData.avgFailedTimesCrossedDefensesTele.a.pc", "timesFailedCrossedDefensesTele.a.pc");
            put("calculatedData.avgFailedTimesCrossedDefensesTele.a.cdf", "timesFailedCrossedDefensesTele.a.cdf");
            put("calculatedData.avgFailedTimesCrossedDefensesTele.b.mt", "timesFailedCrossedDefensesTele.b.mt");
            put("calculatedData.avgFailedTimesCrossedDefensesTele.b.rp", "timesFailedCrossedDefensesTele.b.rp");
            put("calculatedData.avgFailedTimesCrossedDefensesTele.c.db", "timesFailedCrossedDefensesTele.c.db");
            put("calculatedData.avgFailedTimesCrossedDefensesTele.c.sp", "timesFailedCrossedDefensesTele.c.sp");
            put("calculatedData.avgFailedTimesCrossedDefensesTele.d.rw", "timesFailedCrossedDefensesTele.d.rw");
            put("calculatedData.avgFailedTimesCrossedDefensesTele.d.rt", "timesFailedCrossedDefensesTele.d.rt");
            put("calculatedData.avgFailedTimesCrossedDefensesTele.e.lb", "timesFailedCrossedDefensesTele.e.lb");
            put("calculatedData.overallSecondPickAbility", "calculatedData.overallSecondPickAbility");
        }
    };
}
